spring.application.name: SJWSpring

#DB 접속
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
  #LiveReload 설정
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

#MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-alias-package: com.example.sjw.SJWSpring
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'

#Server port
server:
  port: 8081






